/*
 * --------------------------------------------------------------------------
 * Suprema - Entrapass Integration Tool
 * Developed by SDG Systems and Solutions, All rights reserved
 * BioStar 2 and it's trademarks belong to Suprema Inc. 
 * Entrapass and it's trademarks belong to Kantech.
 * --------------------------------------------------------------------------
 */
const DEBUG = false;
if (!DEBUG) {
    console.log = function () {}
}
const lang = {
    en: {
        datatable: "",
        notactivated: ["Non Licensed", "This module hasn't been licensed yet<br>You won't be able to use it until a proper license key is applied, please conctact your vendor<br><i><b>Go to Settings to Activate a License</b></i>"],
        username: "Username",
        password: "Password",
        loginbtn: "Login",
        login: "Login Succedeed!",
        loginexpired: "Login expired!",
        notvaliduser: "Not a user with priviledges, please another user...",
        wronglogin: "Username/Password incorrect, please try again...",
        loginerror: "Error contacting server, please try again...",
        logincompromised: "Login Data has been altered, contact your security department",
        logoutredirection: "You will be redirected to the Login Page",
        socketmsgerror: "Credentials expired!, please login again",
        modaltitle: "You are about to Logout...",
        modaltext: "Press Accept to logout, and press Cancel to close this dialog and go back",
        cancel: "Cancel",
        accept: "Accept",
        close: "Close",
        save: "Save",
        about: ["About", "Version"],
        menu: "Menu",
        confoptions: "Configuration Options",
        langlabel: "Language:",
        sessiontimeoutlabel: "Session Timeout (Minutes)",
        optionstext: "Available Settings to set configurations, please be aware that any changes made here will take effect immediately",
        optionsnote: "<b>NOTE:</b> Change what you need, leave the rest unchanged",
        devicestitle: "Configurations",
        devicestext: "It will allow you to configure the behavior of the integration in terms of the menus that you can see below",
        usertext: "Users",
        devstext: "Devices",
        enrolltext: "Enroll",
        beforeproceed: "Before continuing",
        beforeproceedtext: "Changes will be applied immediately, please review before you hit OK",
        beforeresync: "This procedure will delete de existing data from the device and re-sync.<br>The authentication performance may be affected if the synchronization is not properly configured.<hr>Shall we continue?",
        deleteresync: ["Devices in Sync process: ", "<br>Device(s) ID: ", "It could take several minutes to complete the synchronization (devices need to be online to successfully complete the process)."],
        applysuccess: "Applied Successfully",
        language: ["Language", "Applied Successfuly"],
        success: "Success",
        report: "Report",
        successtext: "Fingerprint successfully added to user <b>ID: ",
        error: "Error",
        errortext: "Could NOT add the Fingerprint",
        errorformats: "Could NOT save Wiegand Formats",
        errorsync: "Could NOT Sync Users",
        placefinger: "Place finger to Scan fingerprint",
        placefingeragain: "Place the SAME finger once again",
        fingersameuser: "Fingerprint Belongs to the <b>SAME User</b>",
        fingerbelongs: ["Fingerprint Belongs to User <b>ID: ", "</b><br>Please scan another Person"],
        quality: "Quality: ",
        belowquality: "Below Quality, Scan Again",
        devicesadd: "DEVICES",
        usersync: "USERS",
        configuration: "CONFIGURATION",
        lblenroll: "PRE-ENROLLMENT",
        settings: "System Settings",
        user_id: "User ID",
        user_name: "Personnel Name",
        user_status: "Active",
        user_email: "E-mail",
        user_ncards: "# Cards",
        user_cards: "Cards",
        user_img: "Profile Image",
        user_fingers: "# Fingers",
        user_faces: "# Faces",
        beforesync: "Users will now be synchronized between Entrapass and the Suprema Database<br>This process might take some time,<br>please be patient",
        user_syncstart: "Sync process has started, you will be able to look at the progress in the Progress panel above.<hr>Once the process finishes a report will be made available for you to see the overall results",
        user_synced: ["Success!", "Device(s) successfully synced<hr><small>The Sync process may take some time to finish, please be patient</small>"],
        device_id: "Device ID",
        status: "Status",
        model: "Model",
        device_name: "Name",
        usersynctitle: "Users",
        usersynctext: "You can use this Feature to batch sync All users from Entrapass into Suprema Devices",
        scandevstext: "Available Users in Entrapass",
        usersyncbtn: "Sync",
        syncusertext: "Card Format Settings<br>for Suprema Devices",
        placecard: "Please place the Card on the Selected Device",
        adddevstitle: "Add/Update",
        adddevstext: "Allows you to manage devices in the system. Once selected, click to ADD. Currently added Devices will appear on the left side (if any)",
        curdevstext: "Devices currently added",
        devsaddtxt: "Search for New Devices",
        searchn_label: "Normal Search",
        searcha_label: "Advanced Search",
        btnsearch: "Search",
        devip_label: "Device IP Address",
        devport_label: "Device Port",
        search_label: "Searching for new Devices, please wait",
        nonewdevs: "NO New devices where found",
        dev_address: "Address",
        connectable: "Connectable",
        notconnectable: "Not Connectable",
        devadding_info: "Adding Device(s) please wait",
        devadding_succ: "Device(s) Added Successfully",
        devadding_err: "Could NOT add Device(s)",
        emptyfields: "IP and Port CANNOT be empty",
        activation: "License activated successfully",
        activationerror: "Could NOT activate License",
        backendnotrunning: ["Service Not running", "The necesary service(s) are not running, please make sure the proper access and admin permissions are set so that services can be up and running"],
        changelic: "The current license data will be deleted from the system<br><i>[If the New license you are about to validate results in error, the system will be put offline]</i>",
        settings_sysstatuslabel: "System Status",
        settings_b2_label: "BioStar 2 Service Status:",
        settings_b2_sys: "BioStar 2 Settings",
        settings_test: "Test Connection",
        settings_save: "Save Credentials",
        settings_setinit: "Set Initial Configurations",
        settings_ccenc: "Encrypt",
        settings_cccert: "Trust Server Certificate",
        licenselabel: "License",
        placeholderlic_key: "Enter the license Key here",
        placeholderlic_customer: "Customer Name",
        lic_val_btn: "Activate Online",
        lic_val_off_btn: "Activate Offline",
        lic_empty_field: "Valid data must be entered into License Key",
        lic_empty_fields: "Valid data must be entered into Customer and License Key",
        licexp: "Expiration: ",
        lic_chng_btn: "Change License",
        syslabel: "System",
        devuserssynclabel: "Users & Devices Sync Time in minutes (setting to zero will disable the Autosync):",
        devuserssync: "Value MUST be greater than cero",
        devuserssync_btn: "Set Sync Time",
        mustfill: "Make sure you have filled in all required fields",
        testsuccess: "Connection Success",
        savedsuccess: "Saved Successfully",
        licoptsuccess: "License Option successfuly configured",
        licoptpresent: "Successful Revision",
        licopterror: "Could not configure License Option",
        wiegandformat: "Wiegand Format",
        beforewformat: "Changes will be applied immediately, these settings will change the way the Devices do the handshake with the Controller, please make sure you know what you're doing",
        wiegand_fields: ["Wiegand ID", "Format Name", "Bits in Format"],
        pleasewait: "Working, please wait",
        one_wformat: "At this time only ONE Wiegand format is supported (besides the <i>MIFARE Format (32 bits)</i>), please make sure you select the appropiate one for your system.",
        deviceidadd: ["Configured", "Allowed Devices", "Devices' ID not licensed", "<b>NOTE: </b><i>These Devices will not be added to this System until they are licensed, please contact your local vendor</i>"],
        wformaterror: "Could not configure Wiegand MiFare 32 bit format",
        devsnotregistered_err: "Could NOT add Device(s)<br><b>Reason:</b> one or more devices are not licensed, please contact your provider",
        offline_fields: ["Offline License Validation", "Generate *.req File", "1. First, click the <i>Generate *.req File</i> button, after that please send the resultant *.req file to your sales representative", "2. Your sales representative will answer back with a *.lic file, once you get that file load if from here to complete the <b>Offline Activation Process</b>"],
        mintimeout: ["Configuration Error", "Minimum Timeout time for the session MUST be greater than Zero"],
        lblsyslic: "Integration License Status:",
        lblsysolic: "Other Server Licenses Activation:",
        lbloffdevs: ["Offline Devices License Validation:", "Please select the *.sdg license file given to you by your local provider"],
        lbldeletedevice: "Delete Device(s)",
        lblresyncdevice: "Resync Device(s)",
        menucformat: "Card Formats",
        menucloud: "Cloud",
        menusmtp: "SMTP",
        menucloud_head: "License for Cloud Access",
        menucloud_lbl: "In order to have access to the Cloud configuration you must have a Suprema Access Control valid License applied (Standard or higher)",
        menucloud_en: "Cloud Active",
        menucloud_help: "Subdomain Name, e.g., https://subdomain.biostar2.com",
        subdomain: "subdomain",
        adminemail: "Administrator e-mail",
        cloudlic: "You are about to change the Suprema Access Control license for the Cloud usage.<br>This feature may not work until you apply a valid license once again.<hr>Are you sure to proceed?",
        cloudmsg: "Changes to this setting require the Server restart in order to take effect.<br>You might not be able to use the system until the process is completed.<hr>Shall we continue?",
        cloudinfo: "System may take some time to be fully respondant again, if you experience some numbness please wait a bit before trying again",
        smtpsrv: "Server Address",
        smtpport: "Server Port (default: 25)",
        smtpusr: "e-mail User Account",
        smtppwd: "User Account Password",
        smtptypelbl: "Security Type",
        smtptestemail: "e-mail for Connection Test",
        smtptest: "Test Connection",
        smtphead: "SMTP Settings",
        vfact: "Remote Pre-enrollment Status",
        vftitle: "E-mail Title",
        vfname: "Company Name",
        vflogolbl: "Company Logo:",
        vfsender: "Sender e-mail",
        vfpolicy: "Footer (Policy Text)",
        vferror: "Error while parsing file",
        lblenroll: "PRE-ENROLLMENT",
        penroll_head: "Pre-Enrollment",
        penroll_headlbl: "The Data shown in this dialog will allow you to selected and individually or masively send an E-mail to users to enable Facial Biometrics Pre-Enrollment from their mobile devices",
        penroll_card: "Users available for pre-enrollment",
        penroll_notice: "An E-mail with a link will be sent with the instructions to complete the Pre-enrollment. This might take some time depending on the amount of users selected<br>Shall we proceed?",
        penroll_btn: "Send Pre-enrollment link",
        penroll_err: "Could not succeed sending the Pre-enrollment links",
        penroll_conferr: ["The field(s) in <i>'false'</i> in the following configuration summary need to be configured before sending Pre-enrollment Links:", '<div style="text-align: left;"><hr><b>Cloud: </b>', "<br><b>SMTP: </b>", "<br><b>Pre-enrollment Settings: </b>"],
        penroll_without: ["IMPORTANT:", "Only ", ", out of ", " selected Users have an E-mail registered in their profile.<hr><i><small>Please note that only Users <b>WITH</b> an E-mail will be operated</small></i>", "Confirm to continue", "You must confirm before continue", "Continue"],
        penroll_sent: "% from the total selected users with e-mail were successfully sent",
        penroll_sel: ["Select All", "Select None"],
        lblkiosk: "KIOSK",
        page_sel: ["Select Page", "Deselect Page"],
        dev_delerr: ["Reason", "Device is used by a door"],
        priv_lbl: "Enrollment Devices filtering according to Entrapass Operator's privileges",
        priv_id: "Priv. ID",
        priv_name: "Privilege Name",
        devg_id: "Group ID",
        devg_name: "Group Name",
        rels_btn: "Delete Filter",
        saverels_err: "Could not save Settings",
        priv_rels: "Add Filter",
        warning: "WARNING!!!",
        beforeclearances: "If you activate this option <b>ALL Users</b> will be <i>deleted</i> from <b>ALL Devices</b> and the access may be interrupted until you perform a Clearance Sync to the Suprema devices.<hr><b>PLEASE:</b> make sure you have properly configured the Suprema Device ID within the Reader Name in Entrapass prior performing <b>any</b> change (if you have doubt on how to properly configure this, please look at <a href='./media/UsersbyClearance.pdf' target='_blank'>this Configuration GUIDE</a>)<br><i>if the Configured ID does not match any Suprema Device ID, the information WILL NOT be sync correctly and users may loose complete access through doors</i><hr>This is a <b>MAJOR CHANGE</b> and once done CANNOT be UNDONE, <i>make sure you understand this warning before proceeding</i>",
        beforerollback: "If you desactivate this option <b>ALL Users</b> will be automatically send to <b>ALL Devices</b><hr><b>PLEASE:</b> note that if the amount of users you have on the system overpasses the Device Capacity Sync errors may occur<hr>Shall we proceed?",
        beforeproimages: "Using the Entrapass Personnel Profile Pictures as Facial Pre-enrollment Data will cause the System to perform a prior check on Facial Quality.<br>Activating this option may introduce a significant increase of time while syncing Users from Entrapass to Suprema Devices<hr>Shall we Proceed?",
        cle_sync: "Sync by Clearance",
        img_sync: "Facial Pre-enrollment",
        use_cle: "Segment users on devices by Clearances",
        use_imgs: "Use Entrapass Personnel Images (for Facial Pre-enrollment)",
        beforesyncCle: "The users will now be synchronized between Entrapass and the Suprema Devices.<br>Making segmentation in Suprema Devices by the Entrapass Clearances<hr>This process might take some time,<br>Shall we procced?",
        beforesyncImg: "The Integration will attempt to use the user Pictures in each Personnel Profile as Facial Pre-enrollment.<br>If the process goes correctly the Pre-enrollment data will be authomatically downloaded to the Suprema Devices<hr>This process might take some time,<br>Shall we procced?",
        qruse_lbl: "Integrate Entrapass Visitor QR to Suprema Devices",
        qrcard: "Create Credential for Visitors Automatically",
        qruse: "Read QR from Entrapass Visitors in Suprema Devices",
        empty_users: "You must select at least ONE user before proceeding...",
        users_lbl: "Selected User records: ",
        sel_type: ["All", "Page"],
        kiosk_txt: ["License Activated, type: <b>Server Kiosk</b>", "License Activated, type: <b>Kiosk Client</b>", "No suitable license found"],
        kiosk_head: "Auto-enrollment Kiosk",
        kiosk_headlbl: "This feature will enable you to configure licenses and further behaviour for Auto-enrollment Client Kiosks",
        kiosk_card: "Client Kiosk License pool",
        kilbl_ava: " Available Licenses:",
        kilbl_act: " Licenses Used:",
        kilbl_tot: " Total Licenses:",
        kilbl_head: "Add more Client Kiosk Licenses here",
        kilbl_add: "Please select the *.sdg license file given to you by your local provider"
    },
    es: {
        datatable: "locale/es-ES.json",
        notactivated: ["No Licenciado", "Este módulo NO ha sido licenciado todavía<br>No podrá usarlo hasta que se active propiamente, por favor contacte al proveedor<br><i><b>Vaya a Ajustes para activar su Licencia</b></i>"],
        username: "Usuario",
        password: "Contraseña",
        loginbtn: "Entrar",
        login: "¡Entrada Exitosa!",
        loginexpired: "¡Credenciales Expiradas!",
        notvaliduser: "Usuario sin privilegios, pruebe con otro usuario...",
        wronglogin: "Usario/Contraseña incorrectos, pruebe nuevamente...",
        loginerror: "Error contactando al servidor, pruebe nuevamente...",
        logincompromised: "Credenciales alteradas, por favor contacte a su departamento de seguridad",
        logoutredirection: "Será redirigido a la página de entrada",
        socketmsgerror: "Credenciales expiradas, por favor vuelva a logearse",
        modaltitle: "Está a punto de Salir...",
        modaltext: "Clic a Aceptar para salir, o clic a Cancelar para cerrar este diálogo y volver",
        cancel: "Cancelar",
        accept: "Aceptar",
        close: "Cerrar",
        save: "Guardar",
        about: ["Acerca de", "Versión"],
        menu: "Menú",
        confoptions: "Opciones",
        langlabel: "Lenguaje:",
        sessiontimeoutlabel: "Timeout de Sesión (Minutos)",
        assigncountlabel: "Asignar Cuenta Manualmente",
        assigncounttext: "El Valor DEBE ser mayor a cero",
        resetcount: "Resetear Cuenta",
        optionstext: "Ajustes disponibles para configurar. Todo cambio que haga acá se aplicará de inmediato, hágalo con cuidado",
        optionsnote: "<b>NOTA:</b> Cambie lo que necesite, deje lo demás como está",
        devicestitle: "Configuraciones",
        devicestext: "Le permitirá configurar el comportamiento de la integración en cuanto a los menús que puede ver a continuación",
        usertext: "Usuarios",
        devstext: "Dispositivos",
        enrolltext: "Enrolar",
        beforeproceed: "Antes de Proceder",
        beforeproceedtext: "Estos cambios se aplicarán de inmediato<br>¿está seguro?",
        beforeresync: "Este procedimiento eliminará los datos existentes del dispositivo y los volverá a sincronizar.<br>El rendimiento de la autenticación puede verse afectado si la sincronización no está configurada correctamente.<hr>¿Continuamos?",
        deleteresync: ["Dispositivos en proceso de sincronización: ", "<br>ID de dispositivo(s): ", "Podría tomar varios minutos completar la sincronización (los dispositivos deben estar en línea para completar exitosamente el proceso)."],
        applysuccess: "Aplicado Correctamente",
        language: ["Lenguaje", "Aplicado Correctamente"],
        nodevserror: "Al menos UNA puerta/dispositivo debe seleccionarse como Entrada/Salida y Actuador(es)",
        success: "Exitoso",
        report: "Reporte",
        successtext: "Huella agregada correctamente a Usuario <b>ID: ",
        error: "Error",
        errortext: "NO se pudo agregar la huella digital",
        errorformats: "NO se pudo guardar los Formatos Wiegand",
        errorsync: "NO se pudo sincronizar correctamente los Usuarios",
        placefinger: "Coloque el dedo para escanear su huella",
        placefingeragain: "Coloque el MISMO dedo una vez más",
        fingersameuser: "La Huella pertenece al <b>MISMO usuario</b>",
        fingerbelongs: ["La Huella pertenece al Usuario <b>ID: ", "</b><br>Por favor escanee a otra persona"],
        quality: "Calidad: ",
        belowquality: "Calidad baja, escanee de nuevo",
        devicesadd: "DISPOSITIVOS",
        usersync: "USUARIOS",
        configuration: "CONFIGURACIÓN",
        lblenroll: "PRE-ENROLAMIENTO",
        settings: "Ajustes de Sistema",
        user_id: "ID de Usuario",
        user_name: "Nombre de Personal",
        user_status: "Activado",
        user_email: "E-mail",
        user_ncards: "# Tarjetas",
        user_cards: "Tarjetas",
        user_img: "Imagen de Perfil",
        user_fingers: "# Huellas",
        user_faces: "# Rostros",
        beforesync: "Los usuarios serán ahora sincronizados entre Entrapass y la Base de datos Suprema<br>Este proceso puede tomar algún tiempo,<br>por favor tenga paciencia y espere a que finalice",
        user_syncstart: "El proceso de sincronización ha comenzado, podrá ver el progreso en el panel Progreso de arriba.<hr>Una vez que finalice el proceso, habrá un informe disponible para que pueda ver los resultados generales.",
        user_synced: ["¡Exitoso!", "Dispositivo(s) sincronizado(s) exitosamente<hr><small>El proceso de sincronización puede tardar algún tiempo en finalizar, tenga paciencia</small>"],
        device_id: "ID de Dispositivo",
        status: "Estado",
        model: "Modelo",
        device_name: "Nombre",
        usersynctitle: "Usuarios",
        usersynctext: "Puede usar esta funcion para sincronizar por lotes los usarios existentes en Entrapass hacia los Dispositivos Suprema",
        scandevstext: "Usuarios disponibles en Entrapass",
        usersyncbtn: "Sincronizar",
        syncusertext: "Ajustes para Formato de Tarjetas<br>para dispositivos Suprema",
        placecard: "Por favor coloque la Tarjeta sobre el Dispositivo Seleccionado",
        adddevstitle: "Agregar",
        adddevstext: "Le permite administrar dispositivos en el sistema. Busque y seleccione los dispositivos, luego clic en Agregar. Los dispostivos presentes en el sistema (si alguno) aparecerán a la izquierda",
        curdevstext: "Dispositivos Agregados",
        devsaddtxt: "Busqueda de Nuevos dispositivos",
        searchn_label: "Búsqueda Normal",
        searcha_label: "Búsqueda Avanzada",
        btnsearch: "Buscar",
        devip_label: "Dirección IP del Dispositivo",
        devport_label: "Puerto del Dispositivo",
        search_label: "Buscando nuevos dispositivos, por favor espere",
        nonewdevs: "NO se encontraron Nuevos Dispositivos",
        dev_address: "Dirección",
        connectable: "Conectable",
        notconnectable: "No Conectable",
        devadding_info: "Agregando Disposito(s) por favor espere",
        devadding_succ: "Dispositivo(s) agregado Correctamente",
        devadding_err: "NO se pudo agregar Dispositivo(s)",
        emptyfields: "IP y Puerto NO pueden estar vacíos",
        activation: "Licencia activada correctamente",
        activationerror: "NO se pudo activar la Licencia",
        backendnotrunning: ["Servicio(s) NO ejecutándose", "El/los servicio(s) necesarios no se están ejecutando, asegúrese de que los permisos de administrador y acceso adecuados estén configurados para que los servicios puedan estar en funcionamiento"],
        changelic: "Los datos de la licencia actual se eliminarán del sistema.<br><i>[Si la nueva licencia que está a punto de validar da como resultado un error, el sistema dejará de trabajar]</i>",
        settings_sysstatuslabel: "Estatus del Sistema",
        settings_b2_label: "Estatus del servicio BioStar 2:",
        settings_b2_sys: "Ajustes de BioStar 2",
        settings_test: "Probar Conexión",
        settings_save: "Guardar Credenciales",
        settings_setinit: "Configuraciones Iniciales",
        settings_ccenc: "Encriptar",
        settings_cccert: "Certificado de Servidor Confiable (Autofirmado)",
        licenselabel: "Licencia",
        placeholderlic_key: "Escriba la llave de Licencia aquí",
        placeholderlic_customer: "Nombre del Cliente",
        lic_val_btn: "Activar Online",
        lic_val_off_btn: "Activar Offline",
        lic_empty_field: "Datos válidos deben ser ingresados en Licencia",
        lic_empty_fields: "Datos válidos deben ser ingresados en Cliente y Licencia",
        licexp: "Expiración: ",
        lic_chng_btn: "Cambiar Licencia",
        syslabel: "Sistema",
        devuserssynclabel: "Tiempo de sincronización para Usarios & Dispositivos en minutos (configure en CERO para desactivar la sincronización automática):",
        devuserssync: "El Valor debe ser mayor a Cero",
        devuserssync_btn: "Guardar Tiempo de Sincronización",
        mustfill: "Asegúrese de haber llenado todos los campos requeridos",
        testsuccess: "Conexión Exitosa",
        savedsuccess: "Guardado Correctamente",
        licoptsuccess: "Opción de Licencia configurada correctamente",
        licoptpresent: "Revisión Correcta",
        licopterror: "Opción de Licencia no se pudo configurar",
        wiegandformat: "Formato Wiegand",
        beforewformat: "Los cambios se aplicarán de inmediato, estas configuraciones cambiarán la forma en que los dispositivos se comunican con el controlador, asegúrese de saber lo que está haciendo",
        wiegand_fields: ["Wiegand ID", "Nombre del Formato", "No. de Bits"],
        pleasewait: "Trabajando, por favor espere",
        one_wformat: "En este momento solo se admite UN formato Wiegand (además del <i>MIFARE Format (32 bits)</i>), asegúrese de seleccionar el adecuado para su sistema.",
        deviceidadd: ["Configurado", "Dispositivos Permitidos", "ID de Dispositivos NO licenciados", "<b>NOTA: </b><i>Estos Dispositivos no se agregarán a este sistema hasta que se licencien, comuníquese con su proveedor local</i>"],
        wformaterror: "No se pudo configurar el formato Wiegand de 32 bits para MiFare",
        devsnotregistered_err: "NO se pudieron agregar dispositivos<br><b>Motivo:</b> uno o más dispositivos no tienen licencia; comuníquese con su proveedor",
        offline_fields: ["Validación de licencia Offline", "Generar archivo *.req", "1. Primero, clic en el botón <i>Generar archivo *.req</i>, después de eso, envíe el archivo *.req resultante a su representante de ventas.", "2. Su representante de ventas le responderá con un archivo *.lic, una vez que obtenga ese archivo, cárguelo desde aquí para completar el <b>Proceso de activación Offline</b>"],
        mintimeout: ["Error de Configuración", "El Timeout mínimo para la sesión DEBE ser mayor a Cero"],
        lblsyslic: "Estado de la licencia de Integración:",
        lblsysolic: "Activación de otras Licencias para Servidor:",
        lbloffdevs: ["Validación de Licencia de Dispositivos offline:", "Seleccione el archivo de licencia *.sdg que le proporcionó su proveedor local."],
        lbldeletedevice: "Borrar Dispositivo(s)",
        lblresyncdevice: "Sincronizar Dispositivo(s)",
        menucformat: "Formato de Tarjetas",
        menucloud: "Nube",
        menusmtp: "SMTP",
        menucloud_head: "Licencia para Acceso a la Nube",
        menucloud_lbl: "Para poder tener acceso a la configuración de la Nube debe tener aplicada una Licencia válida de Suprema Access Control (Estándar o superior)",
        menucloud_en: "Nube Activa",
        menucloud_help: "Nombre de Subdominio, p.e., https://subdominio.biostar2.com",
        subdomain: "subdominio",
        adminemail: "e-mail del Administrador",
        cloudlic: "Está a punto de cambiar la licencia de Suprema Access Control para el uso de la Nube.<br>Es posible que esta característica no funcione hasta que aplique una licencia válida una vez más.<hr>¿Estás seguro de continuar?",
        cloudmsg: "Los cambios a esta configuración requieren que el servidor se reinicie para que surtan efecto.<br>Es posible que no pueda usar el sistema hasta que se complete el proceso.<hr>¿Continuamos?",
        cloudinfo: "El sistema puede tardar algún tiempo en responder completamente. Si experimenta algunos retrasos, espere un poco antes de volver a intentarlo",
        smtpsrv: "Dirección del Servidor",
        smtpport: "Puerto del Servidor (Predeterminado: 25)",
        smtpusr: "Cuenta de usuario (e-mail)",
        smtppwd: "Contraseña de e-mail",
        smtptypelbl: "Tipo de Seguridad",
        smtptestemail: "e-mail para Prueba de Conexión",
        smtptest: "Probar Conexion",
        smtphead: "Ajustes SMTP",
        vftitle: "Encabezado E-mail",
        vfname: "Nombre de Compañía",
        vflogolbl: "Logo de Compañía:",
        vfsender: "Remitente del E-mail",
        vfpolicy: "Pie de página (Texto de políticas)",
        vfact: "Estatus del Pre-enrolamiento Remoto",
        vferror: "Error al obtener el archivo",
        penroll_head: "Pre-enrolamiento",
        penroll_headlbl: "Los Datos mostrados en este diálogo le permitirán enviar de forma individual o masiva a usuarios seleccionados un correo electrónico con las instrucciones para habilitar la Pre-enrolamiento de Biometría Facial desde sus dispositivos móviles",
        penroll_card: "Usarios disponibles para pre-enrolamiento",
        penroll_btn: "Enviar link para Pre-enrolamiento",
        penroll_notice: "Se enviará un E-mail con un enlace con las instrucciones para completar el pre-enrolamiento. Esto puede llevar algún tiempo dependiendo de la cantidad de usuarios seleccionados<br>¿Continuamos?",
        penroll_err: "No se pudo enviar correctamente los enlaces de Pre-enrolamiento",
        penroll_conferr: ["El/los campo(s) en <i>'false'</i> in en el siguiente resumen de configuración necesita ser configurado antes de poder enviar links de Pre-enrolamiento:", '<div style="text-align: left;"><hr><b>Nube: </b>', "<br><b>SMTP: </b>", "<br><b>Ajustes de Pre-enrolamiento: </b>"],
        penroll_without: ["IMPORTANTE:", "Solamente ", ", de ", " usuarios seleccionados tienen E-mail registrado en su perfil.<hr><i><small>Por favor note que solamente los Usuarios <b>CON</b> E-mail serán operados</small></i>", "Confirmo para Continuar", "Necesita confirmar antes de Continuar", "Continuar"],
        penroll_sent: "% del total de Usuarios seleccionados con e-mail fueron correctamente enviados",
        penroll_sel: ["Seleccionar todos", "Seleccionar Ninguno"],
        lblkiosk: "KIOSCO",
        page_sel: ["Seleccionar Página", "Deseleccionar Página"],
        dev_delerr: ["Razón", "Dispositivo usado por una puerta"],
        priv_lbl: "Filtrado de Dispositivos de Enrolamiento de acuerdo con los privilegios del Operador en Entrapass",
        priv_id: "ID de Priv.",
        priv_name: "Nombre de Privilegio",
        devg_id: "ID de Grupo",
        devg_name: "Nombre de Grupo",
        rels_btn: "Borrar Filtro",
        saverels_err: "Error al guardar configuración",
        priv_rels: "Agregar Filtro",
        warning: "¡¡¡ADVERTENCIA!!!",
        beforeclearances: "Si activa esta opción <b>TODOS los Usuarios</b> serán <i>eliminados</i> de <b>TODOS los Dispositivos</b> y el acceso podrá interrumpirse hasta que ejecute una sincronización de Clearances con los dispositivos Suprema.<hr><b>POR FAVOR:</b> asegúrese de haber configurado correctamente el ID del Dispositivo Suprema dentro del nombre del lector en Entrapass antes de realizar <b>cualquier</b> cambio. (Si tiene dudas sobre cómo configurar esto correctamente, consulte <a href='./media/UsersbyClearance.pdf' target='_blank'>esta GUÍA de Configuración</a>)<br><i>Si el ID configurado no coincide con ningún ID de Dispositivo Suprema, la información NO se sincronizará correctamente y los usuarios podrían perder el acceso completo a través de las puertas</i><hr>Este es un <b>CAMBIO MAYOR</b> y una vez hecho NO SE PUEDE DESHACER, <i>asegúrese de comprender esta advertencia antes de continuar</i>",
        beforerollback: "Si desactiva esta opción <b>TODOS los Usuarios</b> se enviarán automáticamente a <b>TODOS los Dispositivos</b><hr><b>POR FAVOR:</b> tenga en cuenta que si la cantidad de usuarios que tiene en el sistema supera la capacidad del dispositivo, podrían ocurrir errores de sincronización<hr>¿Procedemos?",
        beforeproimages: "El uso de las imágenes de Perfil del Personal de Entrapass como datos de Pre-enrolamiento Facial hará que el sistema realice una verificación previa de la calidad de las Imágenes.<br>Activar esta opción introducirá un aumento significativo del tiempo al sincronizar a los usuarios de Entrapass hacia los dispositivos Suprema.<hr>¿Desea proceder?",
        cle_sync: "Sincronizar por Clearance",
        img_sync: "Pre-enrolamiento Facial",
        use_cle: "Segmentar usuarios en dispositivos por Clearance",
        use_imgs: "Usar imágenes de perfil de Entrapass (para Pre-enrolamiento Facial)",
        beforesyncCle: "Los usuarios ahora serán sincronizados entre Entrapass y los Dispositivos Suprema.<br>Haciendo segmentación en los Dispositivos Suprema por los Clearance de Entrapass<hr>Este proceso puede tomar algún tiempo,<br>¿Continuamos?",
        beforesyncImg: "La Integración intentará utilizar las Imágenes de usuario en cada Perfil de Personal en Entrapass como Pre-enrolamiento Facial.<br>Si el proceso va correctamente los datos de Pre-enrolamiento se descargarán automáticamente a los Dispositivos Suprema<hr>Este proceso puede tomar algún tiempo, <br>¿Continuamos?",
        qruse_lbl: "Integrar el QR de Entrapass Visitor a los Dispositivos Suprema",
        qrcard: "Crear Credencial para Visitantes Automáticamente",
        qruse: "Leer QR de Entrapass Visitor en Dispositivos Suprema",
        empty_users: "Debe seleccionar al menos UN usuario antes de continuar...",
        users_lbl: "Registros de Usuarios Seleccionados: ",
        sel_type: ["Todos", "Página"],
        kiosk_txt: ["Licencia Activada, tipo: <b>Servidor Kiosco</b>", "Licencia Activada, tipo: <b>Kiosco Cliente</b>", "No se encontró ninguna licencia que corresponda"],
        kiosk_head: "Kiosco de Auto-enrolamiento",
        kiosk_headlbl: "Esta característica le permitirá configurar licencias y comportamiento adicional para Kioscos de cliente de Autoenrolamiento",
        kiosk_card: "Grupo de licencias de Kiosco de cliente",
        kilbl_ava: " Licencias Disponibles:",
        kilbl_act: " Licencias Utilizadas:",
        kilbl_tot: " Total de Licencias:",
        kilbl_head: "Agregue más licencias de Kiosco de cliente aquí",
        kilbl_add: "Por favor seleccione el archivo de licencia *.sdg que le proporcionó su proveedor local"
    }
};